--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (1,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (2,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (3,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (4,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (5,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (6,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (7,100,1);
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (8,100,1);
--INSERT INTO INGREDIENT (LABEL) VALUES ('BIG_BUN');
--INSERT INTO INGREDIENT (LABEL) VALUES ('SMALL_BUN');
--INSERT INTO INGREDIENT (LABEL) VALUES ('BIG_WRAP');
--INSERT INTO INGREDIENT (LABEL) VALUES ('SMALL_WRAP');
--INSERT INTO INGREDIENT (LABEL) VALUES ('HOT_SAUCE');
--INSERT INTO INGREDIENT (LABEL) VALUES ('CABBAGE');
--INSERT INTO INGREDIENT (LABEL) VALUES ('FRIES');
--INSERT INTO INGREDIENT (LABEL) VALUES ('SWEET_SAUCE');
INSERT INTO PRODUCT_SIZE (LABEL) VALUES('LARGE');
INSERT INTO PRODUCT_SIZE (LABEL) VALUES('SMALL');
INSERT INTO PRODUCT_SIZE (LABEL) VALUES(null);
INSERT INTO PRODUCT_TYPE (LABEL) VALUES('SHAORMA');
INSERT INTO PRODUCT_TYPE (LABEL) VALUES('KEBAB');
INSERT INTO PRODUCT_TYPE (LABEL) VALUES('PEPSI');
--INSERT INTO STOCK (INGREDIENT_ID, QUANTITY_IN_STOCK,QUANTITY_USED_IN_RECIPE)
--VALUES (1,100,1);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (1,1);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (2,2);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (3,3);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (4,4);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (5,5);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (6,6);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (7,7);
--INSERT INTO STOCK_INGREDIENT (STOCK_ID,INGREDIENT_ID)
--VALUES (8,8);
