INSERT INTO INGREDIENT (ID, ingredient)
VALUES (1, 'BUN');
INSERT INTO INGREDIENT (ID, ingredient)
VALUES (2, 'WRAP');
INSERT INTO INGREDIENT (ID, ingredient)
VALUES (3, 'FRIES');
INSERT INTO INGREDIENT (ID, ingredient)
VALUES (4, 'SWEET_SAUCE');
INSERT INTO INGREDIENT (ID, ingredient)
VALUES (5, 'HOT_SAUCE');
INSERT INTO INGREDIENT (ID, ingredient)
VALUES (6, 'CABBAGE');
